# Generated by Django 4.1.7 on 2023-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='Имя не указано', max_length=50, verbose_name='Имя'),
        ),
    ]
